INSERT INTO employees VALUES (1, 'Jake', 'Lacy', 30, 'M');
INSERT INTO employees VALUES (2, 'Rebecca', 'Ferguson', 27, 'F');
INSERT INTO employees VALUES (3, 'Murray', 'Bartlett', 34, 'F');
INSERT INTO employees VALUES (4, 'Brendan', 'Fraser', 51, 'M');
INSERT INTO employees VALUES (5, 'Isabela', 'Merced', 28, 'F');
INSERT INTO employees VALUES (6, 'Joey', 'King', 35, 'M');
INSERT INTO employees VALUES (7, 'Jennifer', 'Lawrence', 32, 'F');
INSERT INTO employees VALUES (8, 'Mike', 'White', 41, 'M');
INSERT INTO employees VALUES (9, 'Joel', 'Kinnaman', 39, 'M');
INSERT INTO employees VALUES (10, 'Elizabeth', 'Debicki', 45, 'F');

INSERT INTO employee_addresses VALUES (1, 1, 'Cour du Château, 1 Rue Gautier 1er, 77140 Nemours, France');
INSERT INTO employee_addresses VALUES (2, 2, 'Frankfurter Str. 143, 34121 Kassel, Germany');
INSERT INTO employee_addresses VALUES (3, 3, 'Smetanova 203, 250 82 Úvaly, Czechia');
INSERT INTO employee_addresses VALUES (4, 4, 'Stansstaderstrasse 19, 6370 Stans, Switzerland');
INSERT INTO employee_addresses VALUES (5, 5, 'Bahnhofstraße 19, 39576 Stendal, Germany');
INSERT INTO employee_addresses VALUES (6, 5, 'Unit 2 Spring Rd, Tyseley, Birmingham B11 3DJ, United Kingdom');
INSERT INTO employee_addresses VALUES (7, 6, 'Eemweg 1-9, 5215 HM s-Hertogenbosch, Netherlands');
INSERT INTO employee_addresses VALUES (8, 6, 'Roklijf 4, 9300 Aalst, Belgium');
INSERT INTO employee_addresses VALUES (9, 6, 'The Waterfront, Rathmullan Rd, Drogheda, Co. Louth, Ireland');
INSERT INTO employee_addresses VALUES (10, 6, '34 Chatsworth Rd, Lower Clapton, London E5 0LP, United Kingdom');
INSERT INTO employee_addresses VALUES (11, 7, 'Wilhelminapark 1, 5041 EA Tilburg, Netherlands');
INSERT INTO employee_addresses VALUES (12, 8, 'Schulstraße 2, 14715 Schollene, Germany');
INSERT INTO employee_addresses VALUES (13, 9, 'Rue Royale 236, 1210 Saint-Josse-ten-Noode, Belgium');
INSERT INTO employee_addresses VALUES (14, 10, 'Jessop St, Portlaoise, Co. Laois, R32 KV20, Ireland');
INSERT INTO employee_addresses VALUES (15, 10, 'Seftigenstrasse 11, 3007 Bern, Switzerland');